### ISSUE TITLE
Connection problem - Android 4.0.3

### ISSUE THREAD

**Issue by andyb2000** [john-tornblom/TVHGuide#14]
Hi John,
Having problems connecting using the newest/updated version. App has server+port, username+pass. Initially appears to be connecting and then just sits at Loading and doesn't get any further.
In TVH I see:

Apr 14 21:37:49 [   INFO]:htsp: Got connection from 192.168.55.1
Apr 14 21:37:49 [   INFO]:htsp: 192.168.55.1: Identified as user android
Apr 14 21:37:49 [   INFO]:htsp: 192.168.55.1 [ android ]: Welcomed client software: org.tvheadend.tvhguide (HTSPv8)
Apr 14 21:37:49 [   INFO]:htsp: 192.168.55.1 [ android | org.tvheadend.tvhguide ]: Privileges raised
Apr 14 21:37:51 [   INFO]:htsp: 192.168.55.1 [ android | org.tvheadend.tvhguide ]: Disconnected

So it appears the client disconnects too early. I've left it sitting at the "Loading" prompt for a while to see if it was trying to do something on the phone but doesn't get anywhere. tcpdump confirms that no other network activity is seen.

I've also captured logcat from my android (rooted so can help diagnose if needed) which is at: http://pastebin.com/1jQ7UUM9
Which although points at image caching problems (some of my chan's don't have them so understandable) it seems to give up at the end on the connection.

Any ideas?

**Comment by john-tornblom** [comment]
If you disable imagecache, it might work better. I'll try fix that once I
get some spare time

2013/4/14 Andy Brown notifications@github.com

**Comment by john-tornblom** [comment]
one second thought, it seems to be caused by a recording that doesn't have
a channel?? I'll see if I can avoid that exception

2013/4/14 John Törnblom john.tornblom@gmail.com

**Comment by andyb2000** [comment]
Thanks for taking a look, disabled imagecache with no difference (interestingly, still saw the HTSService trying at the icons even when disabled?)
Haven't seen the recording without channel, but its possible as one channel merged recently in the UK (BBC HD) so that may be orphaned. Strangely when its sat on the "Loading" screen I can go into the menu, go into recordings and see a list there so it does appear to be pulling those in.

Any debugging I can carry out to help diagnose?

**Comment by andyb2000** [comment]
Resolved with latest update, thanks @john-tornblom
