### ISSUE TITLE
Force Close 

### ISSUE THREAD

**Issue by oneadvent** [john-tornblom/TVHGuide#4]
I am running tvheadend version: 2.12.99~pulse-4 and on xbmc eden. I downloaded the apk from http://sb1066.homelinux.com/tvhguide/ in January 2012 and I can use it to see the guide but I can't seem to watch LiveTV at all. It force closes and doesn't give a reason why. 

I would be happy to provide logs if you know where I can get some helpful ones from.

**Comment by john-tornblom** [comment]
If the internal player doesn't work, try the external one. MX Player and BS Player have been working for me.
