### ISSUE TITLE
Can't access menu in ice cream sandwich

### ISSUE THREAD

**Issue by samsonious** [john-tornblom/TVHGuide#5]
On a newer android device with no physical menu button there  is no way to setup the server settings.

**Comment by john-tornblom** [comment]
Thanks, I'll have a look at it when I got some time over. Have you had this problem before or was it introduced in the last update I made?

**Comment by samsonious** [comment]
First version ive used, only just found out about it. But there doesnt seem to be a way to get to the menu in the app, my device doesnt have a menu button ( google are phasing them out). So not sure how im meant to configure the settings.

**Comment by Wird** [comment]
I have the same problem on a Sony tablet SGPTSE/S, no access to menu

**Comment by Snippo** [comment]
I can confirm this using Android ICS on a Mele A1000. There is no way to access the menu (menu button doesn't work and the 'soft-button' in the bottom of the screen doesn't show up).

**Comment by john-tornblom** [comment]
Okey, I recompiled the apk with the target api set to 9. Please re-install the app and report back on how it works, I can't test this myself. APK is at the usual place: http://john-tornblom.github.com/TVHGuide/download.html

**Comment by Snippo** [comment]
Wow, you're fast!
I'm playing around with Android a bit so I had to reinstall TVHGuide. I was about to manually copy over the settings again but then I noticed the menu works fine now. :)
Thanks.

**Comment by samsonious** [comment]
Awesome! Thanks man. Works a treat.
