### ISSUE TITLE
TVHGuide on Android 4.1.1 [CM10] Live-TV not working

### ISSUE THREAD

**Issue by vHofer** [john-tornblom/TVHGuide#6]
TVHGuide in the newest version does not work properly when watching Live-TV. EPG is working, but when it comes to watch the selected channel the fullscreen window closes after some seconds. It does not work with any configuration (external player, transcoding, ...)

**Comment by john-tornblom** [comment]
If the external player doesn't work, the problem is not fixable from within TVHGuide.
