### ISSUE TITLE
Unable to play stream.

### ISSUE THREAD

**Issue by dlindh** [john-tornblom/TVHGuide#8]
Hi, when trying to watch tv in the client I get the following error. (In the log of tvheadend)

Oct 21 21:29:34 HTTP: 192.168.1.101: using ticket 7A605C07F0485CB45E5FC8269EF051A8C344F3F1 for /stream/channelid/40
Oct 21 21:29:34 subscription: "HTTP" subscribing on "TV10", weight: 100, adapter: "Philips TDA10023 DVB-C", network: "Com Hem", mux: "Com Hem: 450,000 kHz", provider: "Com Hem", service: "TV10", quality: 100
ct 21 21:29:34 cwc: Obtained key for service "TV10" in 3 ms, from xxx
Oct 21 21:29:35 TS: Philips TDA10023 DVB-C/Com Hem: 450,000 kHz/TV10: MPEG2VIDEO @ #4101: Continuity counter error
Oct 21 21:29:35 TS: Philips TDA10023 DVB-C/Com Hem: 450,000 kHz/TV10: MPEG2AUDIO @ #4357: Continuity counter error
Oct 21 21:29:35 TS: Philips TDA10023 DVB-C/Com Hem: 450,000 kHz/TV10: CA @ #1023: Continuity counter error
Oct 21 21:29:37 MKV: Live stream: Unable to write -- Connection reset by peer
Oct 21 21:29:37 subscription: "HTTP" unsubscribing from "TV10"

Watching the stream from XBMC/VLC etc works fine.

**Comment by john-tornblom** [comment]
I cant do anything without a log from the client. I tried on the same channel just a few minutes ago and it works fine for me (Xperia Arc S).

**Comment by dlindh** [comment]
Hmm, how can I aquire a client log? through logcat or does the app log somewhere?

**Comment by john-tornblom** [comment]
TVHGuide uses the same mediaplayer as the default video player in android (more or less). If logcat doesn't provide any more info, there is not much I can do. 

If you save the stream to the sdcard and it plays OK using android player, tvhguide should be able to play it.
If it doesn't work with internal player, I guess its an android issue and should be reported elsewhere.
